<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <script src="../../js/execute.js"></script>
    <script src="//cdn.jsdelivr.net/jstat/1.2.1/jstat.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/1.1.0/handlebars.js"></script>
    <script src="ember_before.js"></script>

</head>
<body>
<p>Using try catch block in main function</p>

<div id="message"></div>


<script>
    var Person = Ember.Object.extend({

        firstName: null,
        lastName: null,

        fullName: function(key, value, oldValue) {

            if (arguments.length === 1) {
                var firstName = this.get('firstName');
                var lastName = this.get('lastName');

                return firstName + ' ' + lastName;


            } else {
                var name = value.split(' ');

                this.set('firstName', name[0]);
                this.set('lastName', name[1]);

                return value;
            }
        }.property('firstName', 'lastName')
    });

    var person = Person.create();




    var f1 = function () {
        for (var i=0; i<100000; i++){
            person.set('fullName', 'Marija Selakovic');
        }

    };

    var a = execute(f1, 10);
    var mean=mean(a);
    console.log(mean);


    $.ajax({
        url: 'http://localhost:8081',
        data: JSON.stringify({'mark':0,'mean':mean}),
        type: 'POST',
        contentType: 'application/json',
        success: function (data) {

            $('#message').html('done, close browser');


            console.log('Success: ')
        },
        error: function (xhr, status, error) {
            console.log('Error: ' + error.message);

        }
    });

</script>

</body>

</html>